name: Test & Build

on: [pull_request]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Dependencies cache
        id: deps-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lockb') }}
          restore-keys: |
            ${{ runner.os }}-node-modules

      - name: Install dependencies
        run: yarn install

  testing:
    needs: install-dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dependencies cache
        id: deps-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run tests
        run: yarn test:unit

  build-checks:
    needs: install-dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dependencies cache
        id: deps-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Prepare .env
        run: cp .env.ci .env.local

      - name: Build
        run: yarn build
